volumes:
  redis_data:
version: '3'
services:
  app:
    image: nestjs-app:latest
    build: .
    container_name: nestjs-app-env
    ports:
      - "443:443"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
